/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __KNN_CLASSIFIER_ALL_TYPES_H__
#define __KNN_CLASSIFIER_ALL_TYPES_H__

#include <knn_classifier/types/type_definitions.h>


#endif /* __KNN_CLASSIFIER_ALL_TYPES_H__ */
