/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __KNN_CLASSIFIER_TYPE_DEFINITIONS_H__
#define __KNN_CLASSIFIER_TYPE_DEFINITIONS_H__


#endif /* __KNN_CLASSIFIER_TYPE_DEFINITIONS_H__ */
